create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

alter table profiles
  add column if not exists email text;

comment on table profiles is
  'ユーザーごとの権限を管理する。role = admin のユーザーだけが管理者機能を使える。';

create table if not exists diagnosis_histories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  input_preview text not null,
  source_url text,
  total_score integer not null check (total_score >= 0 and total_score <= 100),
  summary text not null,
  is_public boolean not null default false
);

alter table diagnosis_histories
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table diagnosis_histories
  add column if not exists source_url text;

alter table diagnosis_histories
  add column if not exists is_public boolean not null default false;

comment on column diagnosis_histories.user_id is
  'Supabase AuthのユーザーID。SaaS化に備えて診断履歴をユーザーごとに分離する。';

comment on column diagnosis_histories.is_public is
  'trueの場合のみ、全体の高スコアサイト5選にURL・スコア・日時を表示する。本文プレビューやサマリーは公開しない。';

create index if not exists diagnosis_histories_user_created_at_idx
  on diagnosis_histories (user_id, created_at desc);

create index if not exists diagnosis_histories_public_score_idx
  on diagnosis_histories (is_public, total_score desc, created_at desc)
  where source_url is not null;

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

comment on table usage_events is
  '診断実行などの利用回数を記録する。無料枠や有料プラン制限の土台。';

comment on column usage_events.action is
  'diagnosis などの利用アクション名。';

create index if not exists usage_events_user_action_created_at_idx
  on usage_events (user_id, action, created_at desc);

create table if not exists aio_query_researches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_url text,
  created_at timestamptz not null default now(),
  generated_queries jsonb not null default '[]'::jsonb,
  checked_count integer not null default 0 check (checked_count >= 0),
  ai_overview_count integer not null default 0 check (ai_overview_count >= 0),
  ai_overview_rate integer not null default 0 check (ai_overview_rate >= 0 and ai_overview_rate <= 100),
  own_site_citation_count integer not null default 0 check (own_site_citation_count >= 0),
  own_site_citation_rate integer not null default 0 check (own_site_citation_rate >= 0 and own_site_citation_rate <= 100),
  cited_urls jsonb not null default '[]'::jsonb,
  checks jsonb not null default '[]'::jsonb
);

comment on table aio_query_researches is
  'SerpApiを使ったAI Overview実測チェックの結果を保存する。検索結果は変動するため、診断履歴とは別に日時付きで残す。';

comment on column aio_query_researches.checks is
  'クエリ別のAI Overview有無、自サイト引用有無、引用元URLをJSONとして保存する。';

create index if not exists aio_query_researches_user_created_at_idx
  on aio_query_researches (user_id, created_at desc);

create index if not exists aio_query_researches_source_url_created_at_idx
  on aio_query_researches (source_url, created_at desc)
  where source_url is not null;

alter table profiles enable row level security;
alter table diagnosis_histories enable row level security;
alter table usage_events enable row level security;
alter table aio_query_researches enable row level security;

drop policy if exists "Users can read own profile" on profiles;

create policy "Users can read own profile"
  on profiles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can insert own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can update own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can delete own diagnosis histories" on diagnosis_histories;

create policy "Users can read own diagnosis histories"
  on diagnosis_histories
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own diagnosis histories"
  on diagnosis_histories
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own diagnosis histories"
  on diagnosis_histories
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own diagnosis histories"
  on diagnosis_histories
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own usage events" on usage_events;
drop policy if exists "Users can insert own usage events" on usage_events;

create policy "Users can read own usage events"
  on usage_events
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own usage events"
  on usage_events
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own AIO query researches" on aio_query_researches;
drop policy if exists "Users can insert own AIO query researches" on aio_query_researches;
drop policy if exists "Users can delete own AIO query researches" on aio_query_researches;

create policy "Users can read own AIO query researches"
  on aio_query_researches
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own AIO query researches"
  on aio_query_researches
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can delete own AIO query researches"
  on aio_query_researches
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- 管理者にしたいユーザーは、auth.users の id と email を確認して以下を実行してください。
-- insert into profiles (user_id, email, role)
-- values ('ここにユーザーID', 'user@example.com', 'admin')
-- on conflict (user_id) do update set email = excluded.email, role = 'admin';
--
-- 注意:
-- このアプリはNext.js API Route経由で全体ランキングを取得し、
-- ブラウザにはURL・スコア・日時だけを返します。
-- 直接Supabaseクライアントから全体公開行を読む設計にする場合は、
-- 本文プレビューやサマリーを含まない公開用ビューを別途作る方が安全です。
