create table if not exists diagnosis_histories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  input_preview text not null,
  source_url text,
  total_score integer not null check (total_score >= 0 and total_score <= 100),
  summary text not null,
  is_public boolean not null default false
);

alter table diagnosis_histories
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table diagnosis_histories
  add column if not exists source_url text;

alter table diagnosis_histories
  add column if not exists is_public boolean not null default false;

comment on column diagnosis_histories.user_id is
  'Supabase AuthのユーザーID。SaaS化に備えて診断履歴をユーザーごとに分離する。';

comment on column diagnosis_histories.is_public is
  'trueの場合のみ、全体の高スコアサイト5選にURL・スコア・日時を表示する。本文プレビューやサマリーは公開しない。';

create index if not exists diagnosis_histories_user_created_at_idx
  on diagnosis_histories (user_id, created_at desc);

create index if not exists diagnosis_histories_public_score_idx
  on diagnosis_histories (is_public, total_score desc, created_at desc)
  where source_url is not null;

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

comment on table usage_events is
  '診断実行などの利用回数を記録する。無料枠や有料プラン制限の土台。';

comment on column usage_events.action is
  'diagnosis などの利用アクション名。';

create index if not exists usage_events_user_action_created_at_idx
  on usage_events (user_id, action, created_at desc);

alter table diagnosis_histories enable row level security;
alter table usage_events enable row level security;

drop policy if exists "Users can read own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can insert own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can update own diagnosis histories" on diagnosis_histories;
drop policy if exists "Users can delete own diagnosis histories" on diagnosis_histories;

create policy "Users can read own diagnosis histories"
  on diagnosis_histories
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own diagnosis histories"
  on diagnosis_histories
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own diagnosis histories"
  on diagnosis_histories
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own diagnosis histories"
  on diagnosis_histories
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own usage events" on usage_events;
drop policy if exists "Users can insert own usage events" on usage_events;

create policy "Users can read own usage events"
  on usage_events
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own usage events"
  on usage_events
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- 注意:
-- このアプリはNext.js API Route経由で全体ランキングを取得し、
-- ブラウザにはURL・スコア・日時だけを返します。
-- 直接Supabaseクライアントから全体公開行を読む設計にする場合は、
-- 本文プレビューやサマリーを含まない公開用ビューを別途作る方が安全です。
